#!/bin/bash
### BEGIN INIT INFO
# Provides:          eLife
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run /BI/server/bin/eLife if it exist
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

DAEMON=/BI/server/bin/eLife

test -x $DAEMON || exit 0

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
	log_daemon_msg "Starting eLife service" "eLife"
	start-stop-daemon --start --quiet --pidfile /var/run/eLife.pid --name eLife --exec $DAEMON -b|| echo -n " already running"
	log_end_msg $?
}

do_stop() {
	log_daemon_msg "Stopping eLife service" "eLife"
        set +e
        start-stop-daemon --stop --quiet --pidfile /var/run/eLife.pid \
                --name eLife --retry 5
        set -e
        log_end_msg $?
}

case "$1" in
    start)
        do_start
        ;;
    restart|reload|force-reload)
	do_stop
	do_start
        ;;
    stop)
	do_stop
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

