/*
 * Created on Oct 25, 2004
 *
 */
package au.com.BI.GroovyModels;
import au.com.BI.Command.Command;
import au.com.BI.Command.CommandInterface;
import au.com.BI.User.*;


/**
 * @author Colin Canfield
 * 
 * Encapsulates a command to flash generated by a script
 *
 */
public class GroovyModelCommand extends Command implements CommandInterface{

	
	public static int RawText = 1;
	
	public String port;
	
	
	public GroovyModelCommand ()
	{
	    super();
	}

	public GroovyModelCommand (String key,String commandCode, User user)
	{
		super (key,commandCode,user);

	}
	

	public GroovyModelCommand (String key,String commandCode, User user, String extraInfo)
	{
		super (key, commandCode,user,extraInfo);
	}


	
}
