package au.com.BI.GroovyScripts;
import au.com.BI.Command.Command;
import au.com.BI.Command.CommandInterface;
import au.com.BI.User.*;
import java.util.*;


/**
 * @author Colin Canfield
 * 
 * Encapsulates a command to flash generated by a script
 *
 */
public class ScriptCommand extends Command implements CommandInterface{

	private Map keyList;
	
	public static int RawText = 1;
	
	public String port;
	
	
	public ScriptCommand ()
	{
	    super();
	}

	public ScriptCommand (String key,String commandCode, User user)
	{
		super (key,commandCode,user);

	}
	

	public ScriptCommand (String key,String commandCode, User user, String extraInfo)
	{
		super (key, commandCode,user,extraInfo);
	}

	
}
