import mx.controls.listclasses.DataSelector;
import mx.core.View;
import mx.controls.listclasses.DataProvider;

[IconFile("tabComponentIcon.png")] 
intrinsic class mx.controls.TabBar extends mx.core.View
{
   private var CONTENTDEPTH:Number;
   public function TabBar();
   public var __dataProvider:Object;
   public var __get__iconField:Function;
   public var __get__icons:Function;
   public var __get__labelPlacement:Function;
   public var __get__tabSymbol:Function;
   private var __iconField:String;
   private var __icons:Array;
   private var __labelPlacement:String;
   [Inspectable(name="labels", defaultValue="Tab Bar")] private var __labels:Array;
   public var __rowCount:Number;
   private var __tabSymbol:String;
   public var __width:Number;
   [Inspectable(name="selected Index", defaultValue="0")] public var _selectedIndex:Number;
   public var addItem:Function;
   public var addItemAt:Function;
   public var calcPreferredHeightFromData:Function;
   public var calcPreferredWidthFromData:Function;
   public var className:String;
   public var clearSelected:Function;
   public function click(eventObj);
   public var createLabel:Function;
   [Inspectable(name="data", defaultValue="")] public var data:Array;
   public var dataProvider:Object;
   public var enabled:Boolean;
   private function fireChange(ignore:Boolean):Void;
   public var getDataProvider:Function;
   public var getItemAt:Function;
   public var getLength:Function;
   public var getSelectedIndex:Function;
   public var getSelectedIndices:Function;
   public var getSelectedItem:Function;
   public var getSelectedItems:Function;
   public function getTab(index:Number):MovieClip;
   public var getValue:Function;
   function set iconField(field:String);
   function get iconField():String;
   function set icons(arr:Array);
   [Inspectable(defaultValue="")] function get icons():Array;
   private function init(Void):Void;
   public var invUpdateControl:Boolean;
   public var invalidate:Function;
   public var isDragScrolling:Boolean;
   public var isSelected:Function;
   public function keyDown(e:Object);
   public var labelField:String;
   public var labelFunction:Function;
   function get labelPlacement():String;
   [Inspectable(enumeration="left,right,top,bottom"defaultValue="right")] function set labelPlacement(str:String);
   public var lastSelID:Number;
   public var lastSelected;
   public var length:Number;
   static var mixIt1:Boolean;
   static var mixIt2:Boolean;
   public var modelChanged:Function;
   public function moveSelBy(amount:Number):Void;
   public var multipleSelection:Boolean;
   private var oldIndex:Number;
   public function onUpdate();
   private function populateFromParams();
   public var removeAll:Function;
   public var removeItemAt:Function;
   public var replaceItemAt:Function;
   public var rows:Object;
   public var selectItem:Function;
   public var selected:Object;
   public var selectedIndex:Number;
   public var selectedIndices:Array;
   public var selectedItem;
   public var selectedItems:Array;
   public var setDataProvider:Function;
   public var setSelectedIndex:Function;
   public var setSelectedIndices:Function;
   private function size();
   public var sortItems:Function;
   public var sortItemsBy:Function;
   static var symbolName:String;
   static var symbolOwner:Object;
   private var tabContent:MovieClip;
   function set tabSymbol(symb:String);
   function get tabSymbol():String;
   private var tabTracker:Number;
   public var tempLabel:Object;
   public var updateControl:Function;
   public var useHandCursor;
   public var vPosition:Number;
   public var value:Object;
   static var version:String;
};
